env:
    es6: true
    node: true
extends: 'eslint:recommended'
parserOptions:
    sourceType: module
rules:
    indent: off
    linebreak-style: off
    quotes: off
    semi:
        - error
        - always
    max-lines-per-function:
        - warn
        - 50
    complexity:
        - warn
        - 5
    max-nested-callbacks:
        - warn
        - 2
    max-depth:
        - warn
        - 3
    no-console: off
